"""How a phrase gets spoken. There is one answer now.

This file used to hold six: four XTTS presets differing in sampling
parameters, plus F5-TTS with and without stress marks. They existed so a
cloned voice could be judged against something rather than in the abstract —
"is this good?" has no meaning without a second term.

The comparison happened and it finished. F5 with stress marks won, for two
reasons that are worth keeping written down:

    it does not fall apart on long lines. XTTS generates autoregressively, one
    chunk conditioned on the last, and by the end of a long reply the pitch has
    drifted and the delivery has hurried. F5 generates the whole phrase at
    once, so the contour holds from the first word to the last.

    the stress is decided rather than guessed. Russian stress is not derivable
    from spelling, and homographs ("зáмок" / "замóк") are the same letters.
    RUAccent marks every word before the text reaches the model, and this
    checkpoint — a fine-tune on 5000 hours of Russian — was trained on text
    that carried those marks, so they are what it expects. XTTS could not be
    given the same help: it has no grapheme-to-phoneme stage for Russian, and a
    stress mark reaches its BPE tokenizer as an unknown character that splits
    the word into fragments the weights never saw. See tts/README.md.

The catalogue stays as a one-item list rather than collapsing into a bare
constant. Voice manifests on disk record which engine built them, the farm
compares that key before resuming a run, and a directory generated by an XTTS
preset must still be recognisable as such so it can be cleared rather than
silently mixed with F5 phrases.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Engine:
    """One named way of speaking, and what a human needs to choose it."""

    key: str                    # stable id: goes in filenames and JSON
    label: str                  # what the panel shows
    note: str                   # one line on what makes this one different
    model: str = "f5"           # which backend synthesises it
    sampling: dict = field(default_factory=dict)   # backend-specific knobs


ENGINES: tuple[Engine, ...] = (
    Engine(
        key="f5_accent",
        label="F5-TTS с ударениями",
        note="русская модель, дообученная на 5000 часах. Ударение в каждом "
             "слове расставляется заранее (RUAccent) и подаётся модели — "
             "она обучена их читать, так что омографы больше не лотерея",
        model="f5",
        sampling={"accent": True},
    ),
)

DEFAULT = "f5_accent"


def get(key: str) -> Engine:
    """One engine by key, or the default if the key is unknown.

    Falling back rather than raising is deliberate: an engine key reaches here
    from json files written by older versions, and refusing to speak because a
    retired preset was named would take the telephone down over a record of
    something that no longer exists.
    """
    for engine in ENGINES:
        if engine.key == key:
            return engine
    return ENGINES[0]


def known(key: str) -> bool:
    return any(engine.key == key for engine in ENGINES)


def catalogue() -> list[dict]:
    """Every engine, as the panel needs to show it.

    Includes whether it can actually run here. A model whose environment is not
    installed is still listed — the operator should see what the option would
    take — but marked so the panel can say so instead of letting someone start
    a job that fails a minute later.
    """
    out = []
    for engine in ENGINES:
        ready, why = _usable(engine)
        out.append({"key": engine.key, "label": engine.label,
                    "note": engine.note, "model": engine.model,
                    "ready": ready, "why": why})
    return out


def _usable(engine: Engine) -> tuple[bool, str]:
    """Whether this engine can synthesise on this machine, and why not.

    F5 lives in its own virtualenv — it wants transformers>=5 and cannot share
    a process with anything pinned below that — so it is asked about by looking
    for that environment rather than by importing it here, which is exactly
    what the separation exists to avoid.
    """
    from tts import backends

    if backends.available(engine.model):
        return True, ""
    return False, backends.why_unavailable(engine.model)
